### ISSUE TITLE
Malfunction ?

### ISSUE THREAD

**Issue by gtbu** [juek/ExpandableEditor#1]
In my xammp 7.3 - firefox 70 - a klick at 'page' just makes the sidebar double as big with a gap of about 5cm. A click at the 'Text' adds several lines with 'Text'.(Javascript enabled)
A click at the pencil opens ckeditor, which is now broader with a right margin of 5 cm.
A click at 'copy' adds lines with TEST and the other  symbols....
( demo at http://typesetter5.bplaced.net/extedit - the mousepointer is over the last line so that the icons appear ) 
I added a class to the div in manage_section.js in my b2. The function should be integrated.

**Comment by juek** [comment]
Making the editor 1/3 area wider is the sole purpose of the plugin. 
With only a flat section structure, there is no need to expand the editor.
CKEditor will not benefit from the expansion but nested section structures will, as the [screenshot](https://raw.githubusercontent.com/juek/ExpandableEditor/master/expandable-editor-anim.gif) shows. 

I don't exactly understand the other issues you have. The plugin doesn't interfere with section management itself at all. Do you get any JS errors?

**Comment by gtbu** [comment]
I do not mean interfere but that it uses or needs the plugin in the background . I can make  a small film - i cannot upload here. Please wait an hour. The sidebar is now broader but not flexible. Only a broader sidebar can be done with css  and onclick (buttom) and js. I am about to modify the sidebar anyway.

Ps. I have updated the link. In Chrome the malfunction is without a click. The mousepointer is over 'editable text' - the menu is at once open

**Comment by juek** [comment]
Everything works here as expected (FF 70, PHP 7.3, TS 5.1.1-b1)
If you changed the editor area markup in your beta, this might well lead to plugin malfunction.

**Comment by gtbu** [comment]
No i do not test in my beta - in 511b1 ! - there is also a connection to Your 'Hide admin ui' - but it is not not caused by , but influences the function. I must probably test online. In my beta the ckeditor panel has just been shortened with css ( a different length).   - please wait until monday.

**Comment by gtbu** [comment]
I ckecked it online - it was my xampp - something was bent - sorry for the commit -
