### ISSUE TITLE
Prevent expansion for CKE

### ISSUE THREAD

**Issue by mahotilo** [juek/ExpandableEditor#3]
Last change works.
But it so funny when "+" icon hides from you after a click :)

**Comment by juek** [comment]
That's what I meant when I said [consistent behavior of the UI icon](https://github.com/Typesetter/Typesetter/issues/521#issuecomment-575903480)

**Comment by mahotilo** [comment]
I do not know why, but it reminds me of https://en.wikipedia.org/wiki/Useless_machine
Never mind!

**Comment by juek** [comment]
We could add a title to the then empty icon space saying: 
'You cannot click here now, or: You can click here as much as you want. Pick one.'

Im sure, folks carrying towels would love it.

**Comment by mahotilo** [comment]
I was embarrassed to ask for it.

**Comment by juek** [comment]
Here we may fool around – way less watchers (sorry, Florin :)

**Comment by juek** [comment]
When you keep on clicking, the message should come: "By repeatedly clicking, you have given a simple but hidden and useless button great pleasure"

Enough now! Let's do some work

**Comment by juek** [comment]
Er … wait: What do you think about the special CKEditor treatment? Seriously.

**Comment by mahotilo** [comment]
> What do you think about the special CKEditor treatment

'special CKEditor treatment' in what sense?

Sorry, I wasn't here.

**Comment by juek** [comment]
> in what sense?

That it is an expandable-button-killer.

**Comment by mahotilo** [comment]
Expandable-button is extremely useful for Sections editor and only for. 
It can be a part of Sections editor only (inside #ckeditor_area ).
As I see the Sections editor is wrapped by CKE DIVs, does it use CKE API?

**Comment by mahotilo** [comment]
You can make a toolbar at the top of Sections editor. Place Expander button here and move here Clipboard as well.

UPD
Of course, I propose all this as part of integration to the TS.

**Comment by juek** [comment]
> for Sections editor and only for.

Not only. You get larger thumbs in gallery editor and generally wider input fields (depending on the section types)

> As I see the Sections editor is wrapped by CKE DIVs, does it use CKE API?

No. IMO that's just class names and ids from the ancient past, where CKEditor was the only editor.

**Comment by mahotilo** [comment]
> Not only. You get larger thumbs in gallery editor

In this case I prefer to use this button.

![image](https://user-images.githubusercontent.com/14929385/72670631-42bd9b00-3a48-11ea-9983-986bd81d8a08.png)

**Comment by mahotilo** [comment]
Well. Can the '+' button control not style but attribute 'width' of panel? Then it will be possible to detect CKE and use the proper width.

**Comment by juek** [comment]
> Well. Can the '+' button control not style but attribute 'width' of panel?

No, because showing/hiding the panel is done by assigning/removing the 'show_editor' css class.

**Comment by mahotilo** [comment]
So, we need :has() analogue...

**Comment by juek** [comment]
> Then it will be possible to detect CKE and use the proper width.

But we …

1. already detect CKE and also
2. know the width is uses

so why?

**Comment by mahotilo** [comment]
I mean :has() in CSS, not in jquery.

**Comment by mahotilo** [comment]
What about this https://github.com/juek/ExpandableEditor/pull/4 ?

**Comment by juek** [comment]
> What about this #4 ?

What does it different? 
`data.section_type == 'text'` exclusively targets CKEditor

**Comment by mahotilo** [comment]
It detects the moment when I go from e.g. Sections editor to text CKE by clicking inside text section.

UPD
At least when panel is expanded.

**Comment by juek** [comment]
> It detects the moment when I go from e.g. Sections editor to text CKE by clicking inside text section.

It already does

**Comment by juek** [comment]
Have you updated both files from my [last commit](https://github.com/juek/ExpandableEditor/commit/54a9e309f0d00284ecbde5702147395048a384d0) (also [ExpandableEditor.css](https://github.com/juek/ExpandableEditor/blob/54a9e309f0d00284ecbde5702147395048a384d0/ExpandableEditor.css))?

**Comment by mahotilo** [comment]
Indeed.
Maybe it was some game of caching when I switched between different installations,

Sorry. It is better for me to continue in the morning:)
